apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdockerregistery-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appdockerregistery
  template:
    metadata:
      labels:
        app: appdockerregistery
    spec:
      containers:
      - name: appdockerregistery
        image: appdockerregistery.azurecr.io/dockerimage:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: appdockerregistery-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: appdockerregistery
