apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-project-webapi
  labels:
    app: demo-project-webapi
spec:
  progressDeadlineSeconds: 9000
  replicas: 3
  selector:
    matchLabels:
      app: demo-project-webapi
  template:
    metadata:
      labels:
        app: demo-project-webapi
    spec:
      containers:
      - name: demo-project-webapi
        image: appdockerregistery.apzurecr.io/demoproject:latest
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: demo-project-webapi-service
spec:
  selector:
    app: demo-project-webapi
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
